version: "3.5"

services:
  postgres:
    container_name: ${DATABASE_USER}
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      PGDATA: /data/postgres
    volumes:
      - ./db/:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped